/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorSchema: typeof import('./../src/components/partials/toogles/ColorSchema.vue')['default']
    LanguageDropdown: typeof import('./../src/components/partials/dropdowns/LanguageDropdown.vue')['default']
    Logo: typeof import('./../src/components/svg/Logo.vue')['default']
    Navigation: typeof import('./../src/components/navigation/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupLayout: typeof import('./../src/components/layouts/SignupLayout.vue')['default']
    SVGErrorPlaceholder: typeof import('./../src/components/svg/SVGErrorPlaceholder.vue')['default']
    VButton: typeof import('./../src/components/base/button/VButton.vue')['default']
    VButtons: typeof import('./../src/components/base/button/VButtons.vue')['default']
    VCard: typeof import('./../src/components/base/card/VCard.vue')['default']
    VCollapse: typeof import('./../src/components/base/collapse/VCollapse.vue')['default']
    VControl: typeof import('./../src/components/base/form/VControl.vue')['default']
    VDropdown: typeof import('./../src/components/base/dropdown/VDropdown.vue')['default']
    VField: typeof import('./../src/components/base/form/VField.vue')['default']
    VIcon: typeof import('./../src/components/base/icon/VIcon.vue')['default']
    VIconBox: typeof import('./../src/components/base/icon/VIconBox.vue')['default']
    VInput: typeof import('./../src/components/base/form/VInput.vue')['default']
    VLabel: typeof import('./../src/components/base/form/VLabel.vue')['default']
    VLoader: typeof import('./../src/components/base/loader/VLoader.vue')['default']
    VOfflinePrompt: typeof import('./../src/components/base/modal/VOfflinePrompt.vue')['default']
    VPlaceholderPage: typeof import('./../src/components/base/placeholder/VPlaceholderPage.vue')['default']
    VPlaceholderSection: typeof import('./../src/components/base/placeholder/VPlaceholderSection.vue')['default']
    VPlaceload: typeof import('./../src/components/base/loader/VPlaceload.vue')['default']
  }
}
